---
# Kafka topic exporter monitoring
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kafka-topic-exporter
    release: prometheus-operator
  name: kafka-topic-exporter
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    port: metrics
    relabelings:
    - action: labeldrop
      regex: ^pod$
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: kafka-topic-exporter
