kafka_topic_prefix: "{{ env_name }}"
app_es_server_count: "{{ groups['es'] | length }}"
log_es_server_count: "{{ groups['log-es-2'] | length }}"
cassandra_server_count: "{{ groups['cassandra'] | length }}"
log_es_threshold: 30
